"""Integration coverage for the full-text pipeline against a real
Milvus server: a ``TEXT`` column, its BM25-generated ``SPARSEVEC``,
keyword ``MATCH ... AGAINST`` filters, BM25-ranked search, and the
dense+full-text hybrid -- Milvus's flagship 2.5+ feature surfaced as
plain SQL. Requires a real server: Milvus Lite has no BM25 functions
at all."""

from __future__ import annotations

import pytest

pytestmark = [pytest.mark.integration, pytest.mark.dbapi]

CREATE_DOCS = (
    "CREATE TABLE docs ("
    "id BIGINT PRIMARY KEY AUTO_INCREMENT, "
    "content TEXT, "
    "content_sparse SPARSEVEC GENERATED ALWAYS AS (BM25(content)), "
    "embedding VECTOR(4)"
    ") WITH (consistency_level='Strong')"
)
CREATE_SPARSE_INDEX = (
    "CREATE INDEX idx_sparse ON docs (content_sparse) "
    "USING SPARSE_INVERTED_INDEX WITH (metric_type='BM25')"
)
CREATE_DENSE_INDEX = (
    "CREATE INDEX idx_dense ON docs (embedding) USING FLAT "
    "WITH (metric_type='COSINE')"
)

DOCS = [
    {
        "content": "milvus is a vector database for similarity search",
        "emb": [0.9, 0.1, 0.0, 0.0],
    },
    {
        "content": "postgres is a relational database",
        "emb": [0.1, 0.9, 0.0, 0.0],
    },
    {
        "content": "bm25 ranks documents by keyword relevance",
        "emb": [0.0, 0.0, 0.9, 0.1],
    },
]


@pytest.fixture
def docs(conn):
    cur = conn.cursor()
    cur.execute(CREATE_DOCS)
    cur.execute(CREATE_SPARSE_INDEX)
    cur.execute(CREATE_DENSE_INDEX)
    cur.executemany(
        "INSERT INTO docs (content, embedding) VALUES (:content, :emb)",
        DOCS,
    )
    return cur


def test_match_against_filters_by_keyword(docs):
    docs.execute(
        "SELECT content FROM docs WHERE MATCH(content) AGAINST (:q)",
        {"q": "relational"},
    )
    rows = docs.fetchall()
    assert rows == [("postgres is a relational database",)]


def test_order_by_bm25_score_ranks_by_relevance(docs):
    docs.execute(
        "SELECT content FROM docs "
        "ORDER BY BM25_SCORE(content_sparse, :q) DESC LIMIT 2",
        {"q": "vector similarity search"},
    )
    rows = docs.fetchall()
    assert rows
    assert rows[0] == ("milvus is a vector database for similarity search",)


def test_hybrid_dense_plus_bm25(docs):
    docs.execute(
        "SELECT id, content FROM docs HYBRID SEARCH ("
        "embedding <=> :dv WEIGHT 0.5, "
        "BM25_SCORE(content_sparse, :q) WEIGHT 0.5"
        ") RERANK RRF(k=60) LIMIT 3",
        {"dv": [0.9, 0.1, 0.0, 0.0], "q": "keyword relevance"},
    )
    rows = docs.fetchall()
    # Both arms' favorites must surface through the fused ranking.
    contents = {row[1] for row in rows}
    assert "milvus is a vector database for similarity search" in contents
    assert "bm25 ranks documents by keyword relevance" in contents


def test_describe_reports_the_generated_column(docs):
    docs.execute("DESCRIBE docs")
    rows = {row[0]: row for row in docs.fetchall()}
    assert rows["content_sparse"][4] == "generated by BM25(content)"
    assert rows["content"][1] == "VARCHAR(65535)"
