"""Integration coverage for the README's full-text story through the
standard SQLAlchemy surface, against a real Milvus server: a ``Text``
column (Milvus's analyzer-enabled full-text input), a ``SPARSEVEC``
generated by ``Computed("BM25(content)")``, a BM25 sparse index
declared as an ordinary ``Index``, and retrieval via a generic
``func.BM25_SCORE(...)`` ordering -- no dialect-specific query
construct anywhere, which is the claim being verified."""

from __future__ import annotations

import pytest
from milvusql_sqlalchemy.types import SPARSEVEC, VECTOR
from sqlalchemy import (
    BigInteger,
    Column,
    Computed,
    Index,
    MetaData,
    Table,
    Text,
    func,
    insert,
    inspect,
    select,
    text,
)

pytestmark = [pytest.mark.integration, pytest.mark.sqlalchemy]

CONTENTS = [
    "milvus is a vector database for similarity search",
    "postgres is a relational database",
    "bm25 ranks documents by keyword relevance",
]


@pytest.fixture
def docs(engine):
    metadata = MetaData()
    table = Table(
        "sa_docs",
        metadata,
        Column("id", BigInteger, primary_key=True, autoincrement=True),
        Column("content", Text),
        Column("content_sparse", SPARSEVEC(), Computed("BM25(content)")),
        Column("embedding", VECTOR(4)),
        milvusql_consistency_level="Strong",
    )
    Index(
        "idx_sa_sparse",
        table.c.content_sparse,
        milvusql_using="SPARSE_INVERTED_INDEX",
        milvusql_with={"metric_type": "BM25"},
    )
    Index(
        "idx_sa_dense",
        table.c.embedding,
        milvusql_using="FLAT",
        milvusql_with={"metric_type": "COSINE"},
    )
    metadata.create_all(engine)
    with engine.begin() as connection:
        connection.execute(
            insert(table),
            [
                {"content": content, "embedding": [0.1 * i] * 4}
                for i, content in enumerate(CONTENTS, start=1)
            ],
        )
    return table


def test_bm25_score_ordering_through_plain_func(docs, engine):
    with engine.connect() as connection:
        rows = connection.execute(
            select(docs.c.content)
            .order_by(
                func.BM25_SCORE(
                    docs.c.content_sparse, "vector similarity search"
                ).desc()
            )
            .limit(2)
        ).all()
    assert rows
    assert rows[0][0] == CONTENTS[0]


def test_match_against_filter_through_text(docs, engine):
    with engine.connect() as connection:
        rows = connection.execute(
            text(
                "SELECT content FROM sa_docs WHERE MATCH(content) AGAINST (:q)"
            ),
            {"q": "relational"},
        ).all()
    assert rows == [(CONTENTS[1],)]


def test_reflection_still_sees_the_generated_table(docs, engine):
    columns = {
        column["name"] for column in inspect(engine).get_columns("sa_docs")
    }
    assert {"id", "content", "content_sparse", "embedding"} <= columns
