"""Unit coverage for the introspection statements: ``SHOW TABLES``,
``SHOW DATABASES`` and ``DESCRIBE <table>`` -- the surface a person at
a prompt (or an LLM agent choosing what to query) orients with."""

from __future__ import annotations

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.translate]


def test_show_tables_lists_collections(build_call_helper):
    call = build_call_helper("SHOW TABLES")
    assert call.method == "list_collections"
    assert call.kwargs == {}
    rows, description, rowcount, _lastrowid = call.postprocess(
        ["items", "cats"]
    )
    assert rows == [("items",), ("cats",)]
    assert description[0][0] == "table_name"
    assert rowcount == 2


def test_show_databases_lists_databases(build_call_helper):
    call = build_call_helper("SHOW DATABASES")
    assert call.method == "list_databases"
    rows, description, _rowcount, _lastrowid = call.postprocess(["default"])
    assert rows == [("default",)]
    assert description[0][0] == "database_name"


class TestDescribe:
    RAW = {
        "collection_name": "docs",
        "fields": [
            {
                "name": "id",
                "type": 5,
                "params": {},
                "is_primary": True,
                "auto_id": True,
            },
            {
                "name": "content",
                "type": 21,
                "params": {"max_length": 65535},
                "nullable": True,
            },
            {"name": "content_sparse", "type": 104, "params": {}},
            {"name": "embedding", "type": 101, "params": {"dim": 8}},
            {
                "name": "tags",
                "type": 22,
                "element_type": 21,
                "params": {"max_capacity": 50, "max_length": 32},
            },
        ],
        "functions": [
            {
                "name": "content_sparse_bm25",
                "input_field_names": ["content"],
                "output_field_names": ["content_sparse"],
            }
        ],
    }

    def test_dispatches_to_describe_collection(self, build_call_helper):
        call = build_call_helper("DESCRIBE docs")
        assert call.method == "describe_collection"
        assert call.kwargs == {"collection_name": "docs"}

    def test_rows_spell_types_the_way_create_table_reads_them(
        self, build_call_helper
    ):
        """``DESCRIBE`` output round-trips: every ``Type`` cell is a
        spelling ``CREATE TABLE`` itself accepts."""
        call = build_call_helper("DESCRIBE docs")
        rows, description, rowcount, _lastrowid = call.postprocess(self.RAW)
        assert [column[0] for column in description] == [
            "Field",
            "Type",
            "Null",
            "Key",
            "Extra",
        ]
        assert rows == [
            ("id", "BIGINT", "NO", "PRI", "auto_increment"),
            ("content", "VARCHAR(65535)", "YES", "", ""),
            (
                "content_sparse",
                "SPARSEVEC",
                "NO",
                "",
                "generated by BM25(content)",
            ),
            ("embedding", "VECTOR(8)", "NO", "", ""),
            ("tags", "ARRAY<VARCHAR>(50)", "NO", "", ""),
        ]
        assert rowcount == 5

    def test_desc_shorthand_parses_too(self, build_call_helper):
        assert build_call_helper("DESC docs").method == "describe_collection"
